Repository sunsin-shop/sunsin-shop.github.io, pull requests merged in 2025-01, with the labels that each got.

#6 강현룡 프로필 작성
  src/.vuepress/public/images/Devil9.png
  src/.vuepress/public/images/Devil9.png:Zone.Identifier
  src/team/tiger/README.md
Labels: enhancement

#10 Jerry 자기소개 추가
  docs/assets/app-962dc384.js
  docs/assets/index.html-0399e7d4.js
  docs/assets/index.html-101cc773.js
  docs/images/tiger-slamdunk/chill-sketch.jpg
  src/.vuepress/public/images/tiger-slamdunk/chill-sketch.jpg
  src/team/tiger/README.md
Labels: documentation

#31 devil9 resize and :Zone.Identifier file remove
  package.json
  src/.vuepress/public/images/Devil9.png
  src/.vuepress/public/images/Devil9.png:Zone.Identifier
  src/team/tiger/README.md
Labels: bug

#49 docs 삭제
  docs/404.html
  docs/images/tiger-slamdunk/me.png
  docs/images/tiger-slamdunk/me2.png
  docs/index.html
  docs/team/how2pr/index.html
  docs/team/recruit/index.html
  docs/team/tiger/index.html
  docs/team/tiger2agile/index.html
  docs/tech/share/index.html
  docs/tech/share/opensource/index.html
Labels: bug
